spring.application.name=spring-jpa-demo

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=srinidhi
spring.datasource.password=nidhi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8084